Commits to add the OCaml manual to the ocaml.org web site
ocaml/v2.ocaml.org pull request #1023
Opened 2018-09-15 20:46 UTC by pmetzger

This is a bit of a hack, but I think it's the right hack. I've added the html for the 4.07 manual and an infrastructure for later adding the html for later releases. I have _not_ added build infrastructure for the manual, that would be both complicated and (I strongly suspect) not a great savings in labor.

You may wish to examine the commits individually, as the one to add the html files is rather long and not very informative.

2018-09-15 20:47 UTC, pmetzger commented
BTW, arguably, we should use the official manual tarball instead of the version I generated locally as my version is somewhat different (different dates, for example.)

2018-09-16 19:00 UTC, Chris00 requested changes

2018-09-16 19:00 UTC, Chris00 commented on Makefile
> +LATEST = 4.07
There is `LATEST_OCAML_VERSION_MAIN` in `Makefile.common` for this.

2018-09-16 19:00 UTC, Chris00 commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
I rather think the manual (as big "constant" data) rather belongs to https://github.com/ocaml/ocaml.org-media  On the server, this repo is checked out in `../media/` (from the root of this repo).  If the manual files are not present, a warning may be displayed but the build should not fail.

2018-09-16 19:00 UTC, Chris00 commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
If not too much work, it would be good to at least add the navigation header on all pages of the manual.

2018-09-16 19:00 UTC, Chris00 commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
It is fine for the `.md` pages you added to be part of this repository.

2018-09-16 19:08 UTC, pmetzger commented on Makefile
> +LATEST = 4.07
That's one obvious fix to make.

2018-09-16 19:10 UTC, pmetzger commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
I can move the thing to the media repo. Should I be sourcing the official manual for this purpose? Should I also be adding the manual sections to releases so that each release will have its manual visible? Lastly, it would be straightforward, using lambdasoup, to alter the manual pages to add the navigation header, but I believe to do that we would need to get a ruling from @xavierleroy and company — I would like to know their opinion since the manual is not (as such) open source.

2018-09-16 19:11 UTC, pmetzger commented
BTW, just to be clear, please don't commit this until we've sorted out exactly how we want to handle it. What I did as a PR here is a strawman. I think it's not _too_ far from what we want but we should hash it out carefully first.

2018-09-16 19:27 UTC, Chris00 commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
> Should I be sourcing the official manual for this purpose?

Yes, please.  It is it done through a script, this script can be committed to the media repo.

> Should I also be adding the manual sections to releases so that each release will have its manual visible?

That would be great!

For the authorization to add the banner, I'll let @xavierleroy answer — my purpose is simply that it eases going back to other pages of the site from the manual.

2018-09-16 21:04 UTC, pmetzger commented on Makefile
> +	rsync -rltHprogv site/manual/* ocaml.org/manual/
The script would probably be nothing more than wget followed by untar so I'm not sure it is _that_ useful, but if it ends up being more complicated than that, I'll commit such a thing. I'll provide instructions in any case.

2018-09-19 12:54 UTC, pmetzger commented
I think perhaps if @xavierleroy doesn't respond I'll do it for now without the navigation bar. It will be easy to add it later if he gives permission.

2018-09-19 18:28 UTC, xavierleroy commented
I missed this discussion among many others, sorry about that.

I see no licensing issues with adding navigation links.  (You're not changing the contents.)  Please go ahead.

2019-05-10 04:32 UTC, XVilka commented
@pmetzger are there any updates regarding this?

2019-05-14 17:49 UTC, pmetzger commented
@XVilka I guess I dropped the ball on it, didn't I. Do you want to try taking it up again? My free time is pretty restricted for the next few weeks at least.

2020-04-05 09:58 UTC, avsm commented
Fixed in #1110

2020-04-05 09:58 UTC, closed without merging