Fix horizontal scrolling on mobile
ocaml/v2.ocaml.org pull request #1025
Opened 2018-09-22 17:29 UTC by juvirez

Here is a screenshot of the problem: http://take.ms/Nhup7

2018-11-13 22:53 UTC, pw374 commented on site/css/ocamlorg.css
> +    margin-right: 0;
I think that a better fix would be to remove the `padding-left` completely and add `margin-right: 0` without touching `width`.

2018-11-13 22:54 UTC, pw374 requested changes
I think that a better fix would be to remove the `padding-left` completely and add `margin-right: 0` without touching `width`. Please let me know what you think.

2018-11-28 06:37 UTC, pw374 commented
@juvirez

2020-11-08 13:09 UTC, avsm commented
@patricoferris @kanishka-work would either of you be able to look into this one?

2020-11-08 13:24 UTC, patricoferris commented
Sure, it also falls under some other "responsive" bugs I've found such as this `iframe` :))

<img width="885" alt="video-width" src="https://user-images.githubusercontent.com/20166594/98466124-6a434700-21c5-11eb-85f0-f173dae3c16b.png">

2020-11-10 08:40 UTC, avsm commented
Fixed by #1210

2020-11-10 08:40 UTC, closed without merging