update opam metadata to 2.0 format
ocaml/v2.ocaml.org pull request #1051
Opened 2019-03-31 10:07 UTC by avsm

2019-03-31 10:37 UTC, Chris00 requested changes
Thanks for submitting this PR!

2019-03-31 10:37 UTC, Chris00 commented on ocaml-org.opam
> -# for the Gtk tutorial:
I think this comment should stay otherwise it is hard to understand why `lablgtk` (the `2` should be removed, it is a typo) is needed.

2019-03-31 15:22 UTC, avsm commented on ocaml-org.opam
> -# for the Gtk tutorial:
good point! done in 58bf577eb967e7f4494aa6589ac30c295db73294

2019-03-31 18:37 UTC, merged

2019-04-02 09:27 UTC, avsm commented
I just noticed that the dockercloud CI is still hooked in; i've disabled it now to stop the X marks on every PR