sync'ed FR install page
ocaml/v2.ocaml.org pull request #1058
Opened 2019-04-13 21:39 UTC by pveber

Notably, installation instruction for opam (the binary way) was
outdated.

2019-04-13 21:55 UTC, Chris00 requested changes

2019-04-13 21:55 UTC, Chris00 commented on site/docs/install.fr.md
> +* Utiliser [OPAM](#Installation via OPAM), un gestionnaire de paquet spécialisé pour OCaml
This link does not work (neither in GH rendering).  You must use `#Installation-via-OPAM`

2019-04-14 10:49 UTC, pveber commented on site/docs/install.fr.md
> +* Utiliser [OPAM](#Installation via OPAM), un gestionnaire de paquet spécialisé pour OCaml
Thanks, I fixed this link and another which was already broken.

2019-04-14 10:57 UTC, Chris00 approved these changes

2019-04-14 10:59 UTC, merged

2019-04-14 10:59 UTC, Chris00 commented
Thanks.