French translation for pages About, Set, Map, and other minor things
ocaml/v2.ocaml.org pull request #1064
Opened 2019-05-02 21:27 UTC by fccm

2019-07-19 08:36 UTC, Chris00 requested changes

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +quelquechose d'intéressant sur le site web, ils seront plus enclin
quelque chose

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +d'ocaml](https://sympa.inria.fr/sympa/arc/caml-list/).
OCaml

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +domaine OCaml.org. Le nom de domaine a son propre
Le domaine est _ocaml.org_

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +Le site OCaml.org est actuellement géré à l'aide de
Comme il n'est pas en début de phrase, j'écrirais _ocaml.org_

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +* Veuillez créer une scission du dépôt (fork) et utilisez le système
« scission » est un peu étrange non?  Le [livre Pro Git](https://git-scm.com/book/fr/v2/GitHub-Contribution-%C3%A0-un-projet) utilise « dupliquer ».

2019-07-19 08:36 UTC, Chris00 commented on site/about.fr.md
> +  de "requête de fusion" (pull request) pour envoyer des changements.
Guillemets françaises ?  (avec espaces insécables)

2019-07-19 08:39 UTC, Chris00 requested changes

2019-07-19 08:39 UTC, Chris00 commented on site/learn/tutorials/map.fr.md
> +Ce module permet de créer des "associations". Par exemple, disons que
« associations »

2019-07-19 08:44 UTC, Chris00 requested changes

2019-07-19 08:44 UTC, Chris00 commented on site/learn/tutorials/set.fr.md
> +Pour faire une structure de donnée ensemble ("set" en anglais) :
ensemble → de type ensemble
ou le mettre entre guillemets (éviter la confusion avec « together »)

2019-07-19 08:44 UTC, Chris00 commented on site/learn/tutorials/set.fr.md
> +Ici il s'agit d'un ensemble de chaine de caractère (String en anglais).
chaine de caractère → chaîne de caractères
_string_

2019-07-19 08:44 UTC, Chris00 commented on site/learn/tutorials/set.fr.md
> +fonction "remove". Cependant si nous souhaitons enlever plusieurs éléments
remove → `remove`

2019-07-19 21:34 UTC, fccm commented
You can do these changes, it's OK for me :)

2019-10-21 23:07 UTC, zapashcanon commented on site/about.fr.md
> +quelque chose d'intéressant sur le site web, ils seront plus enclin
```suggestion
quelque chose d'intéressant sur le site web, ils seront plus enclins
```

2019-10-21 23:07 UTC, zapashcanon commented on site/about.fr.md
> +# À-propos de ce Site
```suggestion
# À-propos de ce site
```

2019-10-21 23:08 UTC, zapashcanon commented on site/about.fr.md
> +* Être la vitrine publique du langage OCaml,
```suggestion
* être la vitrine publique du langage OCaml,
```

2019-10-21 23:08 UTC, zapashcanon commented on site/about.fr.md
> +* Servir de ressource aux utilisateurs d'OCaml,
```suggestion
* servir de ressource aux utilisateurs d'OCaml,
```

2019-10-21 23:09 UTC, zapashcanon commented on site/about.fr.md
> +* Devenir l'endroit privilégié pour que ces utilisateurs puissent indiquer
```suggestion
* devenir l'endroit privilégié pour que ces utilisateurs puissent indiquer
```

2019-10-21 23:09 UTC, zapashcanon commented on site/about.fr.md
> +* Donner aux visiteurs occasionnels, aux nouveaux utilisateurs,
```suggestion
* donner aux visiteurs occasionnels, aux nouveaux utilisateurs,
```

2019-10-21 23:09 UTC, zapashcanon commented on site/about.fr.md
> +  ainsi qu'à la communauté des programmeurs tous ce qui peut leur être utile
```suggestion
  ainsi qu'à la communauté des programmeurs tout ce qui peut leur être utile
```

2019-10-21 23:09 UTC, zapashcanon commented on site/about.fr.md
> +doivent trouver une utilité à ce site web ou il y aura peu de chance
```suggestion
doivent trouver une utilité à ce site web où il y aura peu de chance
```

2019-10-21 23:11 UTC, zapashcanon commented on site/about.fr.md
> +plus formelle, et tout changement ou discussion par rapport à çà
```suggestion
plus formelle, et tout changement ou discussion par rapport à ça
```

2019-10-21 23:15 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +Bon, nous avons créé le module `MyUsers` and fixant le type des clefs
```suggestion
Bon, nous avons créé le module `MyUsers` en fixant le type des clefs
```

2019-10-21 23:15 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +Hé bien c'est très simple, nous démarrons avec une structure vide
```suggestion
Eh bien c'est très simple, nous démarrons avec une structure vide
```

2019-10-21 23:15 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +alors ajoutons y quelques éléments:
```suggestion
alors ajoutons-y quelques éléments:
```

2019-10-21 23:16 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +a ajouté "fred" et son mot de passe "pruneausucre" à la précédante
```suggestion
a ajouté "fred" et son mot de passe "pruneausucre" à la précédente
```

2019-10-21 23:16 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +Ce qui signifie que notre association de notre module `MyUsers` est
```suggestion
Ce qui signifie que l'association de notre module `MyUsers` est
```

2019-10-21 23:17 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +string vers entier ou une association du type entier vers quoique ce soit
```suggestion
string vers entier ou une association du type entier vers quoi que ce soit
```

2019-10-21 23:17 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +let print_users key password =
```suggestion
let print_user key password =
```

2019-10-21 23:18 UTC, zapashcanon commented on site/learn/tutorials/map.fr.md
> +MyUsers.iter print_users m;;
```suggestion
MyUsers.iter print_user m;;
```

2019-10-22 06:25 UTC, Chris00 commented on site/learn/tutorials/map.fr.md
> +alors ajoutons y quelques éléments:
Il faut aussi un espace insécable devant le « : ».

2019-10-22 06:30 UTC, Chris00 commented on site/learn/tutorials/map.fr.md
> +let print_users key password =
Je viens de changer ça dans les fichiers pour les autres langues.  C'est bien de le faire ici aussi.

2019-10-22 06:30 UTC, Chris00 commented on site/learn/tutorials/map.fr.md
> +MyUsers.iter print_users m;;
ditto.

2019-10-22 06:30 UTC, Chris00 commented
@zapashcanon Merci pour la relecture !

2019-10-23 07:44 UTC, Chris00 commented
Github ne me laisse pas faire un commit avec les modifications proposées.  @fccm Je suppose que vous devez le faire puisque vous possédez la branche.

2019-10-24 03:22 UTC, fccm commented
@kit-ty-kate is able to do it, but I don't know how she does. Maybe we could ask her?

2019-10-31 13:45 UTC, merged