Added Operator Lookup Link in Learning Section
ocaml/v2.ocaml.org pull request #1302
Opened 2021-03-26 06:59 UTC by Aditi-1400

Added operator lookup link in external learning section as per issue #1223.
![Screenshot from 2021-03-26 00-24-51](https://user-images.githubusercontent.com/62544124/112594249-a3a3e880-8e2e-11eb-9e93-567078abf806.png)
I've added the same in index.ja.md, but since I couldn't see any external learning section in index page of other languages, I did not make any changes in them.

2021-03-27 08:15 UTC, patricoferris requested changes
Thanks @Aditi-1400 :)) A few suggestions then it should be good to go.

2021-03-27 08:15 UTC, patricoferris commented on site/learn/tutorials/index.md
> +* [Ocaml Operator Lookup](https://www.craigfe.io/operator-lookup/),
To be consistent with the rest of the site, it should be `OCaml` and not `Ocaml`.

2021-03-27 08:15 UTC, patricoferris commented on site/learn/tutorials/index.md
> +  for getting an explanation on behaviour of a operator or syntax element, along with usage examples.
I think this might read better as "on the behaviour" and it should be "an operator"

2021-03-30 16:58 UTC, merged

2021-03-30 16:58 UTC, avsm commented
Thanks for the contribution! Now merged to the live site.