Makes entire newsfeed list item lead to its respective article when clicked on
ocaml/v2.ocaml.org pull request #1506
Opened 2021-04-11 03:38 UTC by ozmos

# Issue Description

News feed was slightly confusing as some of the elements within each feed item were not linked to the corresponding article.  

Fixes # 1499

## Changes Made

I used javascript to make the entire list item lead to the corresponding news article when clicked on.  I also added hover effects to make it more apparent that the whole item could be clicked on.

I initially tried to alter the markup in *index.md*, wrapping the whole list item in an `a` tag and removing the nested anchor elements.  Unfortunately when the markdown compiled it closed the anchor tag before the list item started, rendering the link unusable.  Thus I had to resort to using javascript to resolve the issue

### Before changes:
![news-before](https://user-images.githubusercontent.com/39433568/114291406-ac94eb00-9ab9-11eb-9c93-a6ee4e1300ff.png)
Clicking on the arrow or anywhere other than the icon or `h1` link doesn't lead to article

### After changes:
![news-after](https://user-images.githubusercontent.com/39433568/114291429-f2ea4a00-9ab9-11eb-9beb-5501e321421a.png)
Clicking anywhere on the list item leads to the corresponding article.  Hovering over list item triggers color changes to highlight 'clickability'.

2021-04-12 07:42 UTC, patricoferris requested changes
Thanks for the PR :))

Sorry for missing your questions https://github.com/ocaml/ocaml.org/issues/1499#issuecomment-817069396. I think there's a more "straightforward" solution which I have outlined in the comments on the code. It doesn't involve any client-side Javascript which I think is more desirable. 

Feel free to ask any questions if anything is unclear.

2021-04-12 07:42 UTC, patricoferris commented on site/css/bootstrap_mod.css
> +/* for improved-news-feed.js - ozmos */
A couple of points: 

 - I don't think you need to add your Github handle to the comment here, if people want to know who made the changes they can you something like git blame. 
 - The naming of the JS file doesn't make a lot of sense in the long run, there's no way of knowing what the improvement is.

2021-04-12 07:42 UTC, patricoferris commented on site/css/bootstrap_mod.css
> +.news-feed li:hover, .news-feed li:focus {
Why are there the same changes in `bootstrap_mod.css` and `ocamlorg.css` -- I would have thought having just the changes in `ocamlorg.css` would be enough?

2021-04-12 07:42 UTC, patricoferris commented on site/js/improved-news-feed.js
> +/* Makes all newsfeed list items lead to their respective articles when clicked on */
I think adding JS isn't necessary to solve this problem. Some of the changes can be done directly on the items in the `index.md` (and `fr`) file such as the the link to the recent compiler release or the link to OCaml Weekly News. 

The other items are generated by the line: 

```
{{! cmd script/rss2html -n 4 --headlines http://planet.ocaml.org/rss20.xml !}}
```

Armed with this knowledge and the file https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml you should be able to do this without adding any Javascript.

2021-04-13 01:18 UTC, ozmos commented
Thanks @patricoferris I'll make those changes

2021-04-18 07:50 UTC, ozmos commented
The top announcements feed is working now by wrapping the `article` element with an `a` tag and adjusting the CSS.  No JS necessary.  
I've tried to replicate this in [https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml) with the following:
```
let html_icon =
    [Element("span", [],
      [Element("img", ["src", img ^ ".svg"; "class", "svg";
                      "alt", img_alt], []);
      Element("img", ["src", img ^ ".png"; "class", "png";
                      "alt", img_alt], [])])] in
  let html_date = match get_date e with
    | None -> html_icon
    | Some d ->
       (* Netdate internationalization functions are more developed. *)
       let d =
         let d = netdate_of_ptime d in
         if Netdate.format ~fmt:"%x" d = Netdate.format ~fmt:"%x" d ~l9n then
           (* English style *)
           Netdate.format ~fmt:"%B %e, %Y" d ~l9n
         else
           Netdate.format ~fmt:"%e %B %Y" d ~l9n in
       Element("p", [], [Data d]) :: html_icon in
  let html_title =
    Element("h1", [], [Data title])in 
      [Element("li", [], 
        [Element("a", ["href", link; "title", title],
          [Element("article", [], html_title :: html_date)]
        )]
      );
   Data "\n"]
```
Which I want to compile to this:
```
<ul class="news-feed">
    <li>
        <a href="community/planet/#be62995dc8d24a69e573e2222e05c7fe" title="New Try-Alt-Ergo">
            <article>
                <h1>New Try-Alt-Ergo</h1>
                <p>March 29, 2021</p><span><img src="img/news.svg" class="svg" alt=""><img src="img/news.png"
                        class="png" alt=""></span>
            </article>
        </a>
    </li>
</ul>
```
But it compiles to this:
```
<ul class="news-feed">
    <a href="community/planet/#be62995dc8d24a69e573e2222e05c7fe" title="New Try-Alt-Ergo"></a>
    <li>
        <article>
            <h1>New Try-Alt-Ergo</h1>
            <p>March 29, 2021</p><span><img src="img/news.svg" class="svg" alt=""><img src="img/news.png" class="png"
                    alt=""></span>
        </article>
    </li>
</ul>
```
I am not at all familiar with *.ml* code so I am guessing I've made some mistakes in the syntax.  Can anyone point out where I've gone wrong and point me in the right direction?

2026-03-22 07:04 UTC, closed without merging