Ocaml version selector looks ugly on firefox
ocaml/v2.ocaml.org pull request #1522
Opened 2021-04-14 20:21 UTC by mercybassey

# the select button on the docs pages looks ugly on firefox

When you navigate to ocaml.org documentation page, there is a select dropdown element for selecting ocaml version. The styling looks elegant when viewed on chrome or opera but it looks a little ugly on firefox.

Fixes #1359

## Changes Made
I added a specific style for the firefox browser to make it a little more presentable

![image](https://user-images.githubusercontent.com/57226464/114773664-3d442300-9d67-11eb-94ab-97e7eb2b9a43.png)

* **Please check if the PR fulfills these requirements**

- [ ] PR is descriptively titled and links the original issue above
- [ ] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

2021-04-14 20:46 UTC, mercybassey commented
![Screenshot from 2021-04-14 21-45-00](https://user-images.githubusercontent.com/57226464/114776823-d0328c80-9d6a-11eb-8b44-9d55a94a43cd.png)
New solution

2021-04-14 22:50 UTC, mercybassey commented
@patricoferris @avsm i'd love to have a review on this. thanks!

2021-04-15 08:08 UTC, patricoferris requested changes
Thanks for the contribution, I've suggested a few changes. 

I'm wondering if you found any other advice about using `@-moz-document`? The only documentation I found seemed to suggest maybe not to use it ?

2021-04-15 08:08 UTC, patricoferris commented on site/learn/portability.md
> +<td></td>
I'm guessing these changes are also related to the table CSS changes?

2021-04-15 08:08 UTC, patricoferris commented on site/css/bootstrap.css
> +
I'm not quite sure how this is related to this PR -- I think someone else has been working making a table look better #1359? If it isn't related can you remove these changes please.

2021-04-15 08:08 UTC, patricoferris commented on site/css/bootstrap.css
> +@-moz-document url-prefix() {
I'm not entirely convinced by this approach. 

A quick glance at https://developer.mozilla.org/en-US/docs/Web/CSS/@document suggests `@document` is deprecated and further down the page: 

> There is a -moz-prefixed version of this property — @-moz-document. This has been limited to use only in user and UA sheets in Firefox 59 in Nightly and Beta — an experiment designed to mitigate potential CSS injection attacks

So I don't know if this is really going to solve our problem for all Firefox versions

2021-04-15 08:20 UTC, mercybassey commented
@patricoferris  I'll do a deep research on this to see if  there's a better approach to resolve this. Thanks

2021-04-15 19:17 UTC, CQW-Code commented
Perhaps create a dropdown with Bootstrap and style it through the CSS?  That may make the selector dropdown look the same across most browsers.  Just off the top of my head- I'd have to read up on Bootstrap (I'm used to Semantic and Material UI).  Just a humble observation :).

2021-04-16 06:41 UTC, mercybassey commented
@CQW-Code thank you. I'd give it a shot

2021-04-17 06:53 UTC, mercybassey commented
new solution
![Screenshot from 2021-04-17 07-51-24](https://user-images.githubusercontent.com/57226464/115104664-e5b5db00-9f51-11eb-8c1c-bd48c8ce66ed.png)

@patricoferris i'd like you to review

2021-04-19 08:25 UTC, patricoferris commented
Hi @mercybassey, thanks for the updates (and thanks for the great suggestions @CQW-Code!)

Looking at the attached screenshot, it appears as if there's some extra padding/margin above the text? Is there anyway you could remove that. 

For example here is the same dropdown on a chromium-based browser, the padding is symmetric.

<img width="325" alt="Screenshot 2021-04-19 at 09 23 41" src="https://user-images.githubusercontent.com/20166594/115204929-f18bd380-a0f0-11eb-95c7-729467480dc1.png">

2021-04-19 08:48 UTC, mercybassey commented
> Hi @mercybassey, thanks for the updates (and thanks for the great suggestions @CQW-Code!)
> 
> Looking at the attached screenshot, it appears as if there's some extra padding/margin above the text? Is there anyway you could remove that.
> 
> For example here is the same dropdown on a chromium-based browser, the padding is symmetric.
> 
> <img alt="Screenshot 2021-04-19 at 09 23 41" width="325" src="https://user-images.githubusercontent.com/20166594/115204929-f18bd380-a0f0-11eb-95c7-729467480dc1.png">

I figured. Will get this done right away. Thanks

2021-04-19 18:43 UTC, mercybassey commented
![Screenshot from 2021-04-19 19-41-13](https://user-images.githubusercontent.com/57226464/115286710-46f2cf80-a147-11eb-8143-0713f18fd2e2.png)

this is a screenshot to the new solution. Added some extra styles. @patricoferris i'd like to know what you think.

2021-04-20 07:50 UTC, patricoferris commented on site/css/bootstrap.css
> +
@mercybassey why are these changes needed?

2021-04-20 08:11 UTC, patricoferris requested changes
@mercybassey this new one looks much better thanks, I've left a few comments

2021-04-20 08:11 UTC, patricoferris commented on site/css/bootstrap.css
> +select::-ms-expand{
This appears to be duplicated?

2021-04-20 08:11 UTC, patricoferris commented on site/css/bootstrap.css
> +select::-ms-expand {
See comment about duplication

2021-04-20 18:31 UTC, mercybassey commented on site/css/bootstrap.css
> +select::-ms-expand {
@patricoferris  made the changes and all is set.

2025-10-12 16:25 UTC, closed without merging