Blogfix
ocaml/v2.ocaml.org pull request #1543
Opened 2021-04-19 21:00 UTC by shreyaswikriti

# Issue Description

Please include a summary of the issue.
Fixed the ordering of blogs ([FIXME](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml#L191)
)by removing the leading whitespace using String.trim function. Now leading whitespace won't impact ordering.

Fixes # 1534

## Changes Made

Please describe the changes that you made.

* **Please check if the PR fulfills these requirements**

- [ ] PR is descriptively titled and links the original issue above
- [ ] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

2021-04-21 16:09 UTC, shreyaswikriti commented
@pitag-ha, Can you please look into this?

2021-04-21 16:33 UTC, gs0510 requested changes
Thanks for your PR @shreyaswikriti! Looks good, some tiny changes needed :)

2021-04-21 16:33 UTC, gs0510 commented on script/rss2html.ml
>    (* Sort by name.  (FIXME: one may want to ignore spaces.) *)
You can remove the FIXME from this comment :)

2021-04-21 16:33 UTC, gs0510 commented on script/rss2html.ml
> +  let trimm str = String.trim str in
You can name this function trim :) Alternatively you don't need to define this and instead can use `String.trim` directly in line 193. :)

2021-04-21 16:45 UTC, shreyaswikriti commented
@gs0510, Thanks for the review, I'll push the suggested changes.

2021-04-27 15:28 UTC, avsm commented
This looks good, thank you for the contribution!

2021-04-27 15:28 UTC, merged