add solution to "English Number Words" challenge
ocaml/v2.ocaml.org pull request #918
Opened 2017-07-03 21:02 UTC by chrismamo1

this might not be an ideal solution to the problem, but it's pretty good and seems to work

2017-07-26 00:26 UTC, Chris00 requested changes
Thanks for your contribution.  May you please address the following remarks?

2017-07-26 00:26 UTC, Chris00 commented on site/learn/tutorials/99problems.md
> +>   let rec aux n =
It would be better to use a more descriptive name than `aux`.

2017-07-26 00:26 UTC, Chris00 commented on site/learn/tutorials/99problems.md
> +>        let buf = Buffer.create 64 in
I think it would be clearer to create the buffer outside of the recursive function and have this function fill the buffer.

2017-07-26 00:26 UTC, Chris00 commented on site/learn/tutorials/99problems.md
> +>       let buf = aux n' in
Not so nice that it is not terminal recursive.  How about creating a list of the strings (which will naturally be in the right order) and then concatenating them (`String.concat`) with `"-"` in between?

2017-07-26 19:10 UTC, Chris00 commented
I wrote a solution in bc57e20dc212b7d57c639acbac2a73c7605d11a0.

2017-07-26 19:10 UTC, closed without merging

2017-07-29 20:50 UTC, chrismamo1 commented
Thanks for the feedback! Sorry I didn't see it soon enough to address the issues (and it looks like a solution already existed in another PR, I should've checked there first).