Update: recursion addendum section
ocaml/v2.ocaml.org pull request #957
Opened 2018-02-20 18:30 UTC by jordalgo

Make a note about the calling of `read_filesystem` instead of `read_directory` to get the whole solution working.

2018-02-22 18:46 UTC, Chris00 requested changes

2018-02-22 18:46 UTC, Chris00 commented on site/learn/tutorials/if_statements_loops_and_recursion.md
> +give up and return the result so far". Also, note that the function name
What function name?

2018-02-22 18:46 UTC, Chris00 commented on site/learn/tutorials/if_statements_loops_and_recursion.md
> +has changed and you're invoking of it will have to change too:
> you're invoking of it

Is this proper English?

2018-02-22 18:46 UTC, Chris00 commented on site/learn/tutorials/if_statements_loops_and_recursion.md
> +```
I do not think the text you added is particularly clear.  May you please improve it?

2018-02-22 19:11 UTC, jordalgo commented
@Chris00 Updated the text I added. Hopefully it's more clear. Not sure why my diff is showing the addition of spaces. Let me know if you need me to delete those.

2018-02-22 19:22 UTC, Chris00 commented
> Let me know if you need me to delete those.

Please do.

2018-02-22 19:30 UTC, jordalgo commented
Done.

2020-09-07 17:17 UTC, samoht commented
@Chris00 are you happy with the new changes?

2020-11-19 11:03 UTC, avsm commented
Thanks for the iteration @jordalgo! I think the newer version is clearer; we can refine it with a followup PR if necessary.

2020-11-19 11:03 UTC, merged